import { describe, expect, it, vi } from 'vitest'

import type { FinanceDataSource } from '@/data/contracts'
import {
  createLocalSyncMetadataUpsertStatement,
  createLocalUpsertStatement,
  hydrateSupabaseToLocalSqlite,
  localHydrationEntityTypes,
} from '@/data/local-sqlite/hydration'
import type {
  LocalHouseholdMemberRow,
  LocalHouseholdRow,
} from '@/data/local-sqlite/local-finance-row-types'
import type {
  LocalSqliteDriver,
  LocalSqliteStatementParams,
} from '@/data/local-sqlite/local-sqlite-types'

class RecordingHydrationDriver implements LocalSqliteDriver {
  committed = false
  failOnSqlIncludes?: string
  rolledBack = false
  runs: Array<{
    inTransaction: boolean
    params?: LocalSqliteStatementParams
    sql: string
  }> = []
  transactionCalls = 0
  private inTransaction = false

  async exec() {
    return undefined
  }

  async query<T>() {
    return [] as T[]
  }

  async run(sql: string, params?: LocalSqliteStatementParams) {
    this.runs.push({
      inTransaction: this.inTransaction,
      params,
      sql,
    })

    if (this.failOnSqlIncludes && sql.includes(this.failOnSqlIncludes)) {
      throw new Error(`planned failure for ${this.failOnSqlIncludes}`)
    }
  }

  async transaction<T>(work: () => Promise<T>) {
    this.transactionCalls += 1
    this.inTransaction = true

    try {
      const result = await work()
      this.committed = true
      return result
    } catch (error) {
      this.rolledBack = true
      throw error
    } finally {
      this.inTransaction = false
    }
  }
}

const now = new Date('2026-06-24T10:00:00.000Z')

const baseRecord = {
  archivedAt: undefined,
  createdAt: '2026-06-20T00:00:00.000Z',
  deletedAt: undefined,
  id: 'record-1',
  updatedAt: '2026-06-21T00:00:00.000Z',
}

const household = {
  archived_at: null,
  created_at: '2026-06-01T00:00:00.000Z',
  created_by: 'user-1',
  currency: 'PKR',
  deleted_at: null,
  id: 'household-1',
  locale: 'en-PK',
  name: 'Umair Family',
  updated_at: '2026-06-02T00:00:00.000Z',
} satisfies LocalHouseholdRow

function createMockFinanceDataSource() {
  const data = {
    accounts: [
      {
        ...baseRecord,
        archivedAt: '2026-06-22T00:00:00.000Z',
        color: '#111111',
        currency: 'PKR',
        currentBalance: 125,
        deletedAt: '2026-06-23T00:00:00.000Z',
        icon: 'Wallet',
        name: 'Cash',
        notes: 'Daily cash',
        openingBalance: 100,
        type: 'cash',
      },
    ],
    bills: [
      {
        ...baseRecord,
        amount: 50,
        categoryId: 'category-1',
        dueDate: '2026-06-24',
        frequency: 'monthly',
        lastGeneratedDate: undefined,
        linkedTransactionId: undefined,
        name: 'Internet',
        nextDueDate: '2026-07-24',
        notes: undefined,
        paymentAccountId: 'account-1',
        status: 'pending',
      },
    ],
    budgets: [
      {
        ...baseRecord,
        categoryId: 'category-1',
        group: 'needs',
        month: '2026-06',
        notes: undefined,
        plannedAmount: 100,
      },
    ],
    categories: [
      {
        ...baseRecord,
        color: '#222222',
        defaultKey: 'food',
        icon: 'Utensils',
        isDefault: true,
        name: 'Food',
        type: 'expense',
      },
    ],
    goals: [
      {
        ...baseRecord,
        color: '#333333',
        currentAmount: 1000,
        icon: 'Target',
        name: 'Emergency',
        notes: undefined,
        priority: 'high',
        status: 'completed',
        targetAmount: 1000,
        targetDate: '2026-12-31',
      },
    ],
    loans: [
      {
        ...baseRecord,
        counterparty: 'Ali',
        dueDate: '2026-08-01',
        interestRate: 0,
        linkedTransactionId: undefined,
        name: 'Loan',
        notes: undefined,
        outstandingAmount: 0,
        principalAmount: 500,
        receivingAccountId: undefined,
        sourceAccountId: 'account-1',
        status: 'completed',
        type: 'given',
      },
    ],
    recurringBills: [
      {
        ...baseRecord,
        amount: 90,
        autoGenerateDaysBeforeDue: 3,
        categoryId: 'category-1',
        endDate: undefined,
        frequency: 'monthly',
        interval: 1,
        isActive: true,
        lastGeneratedAt: undefined,
        lastGeneratedForDate: undefined,
        name: 'Rent',
        nextDueDate: '2026-07-01',
        notes: undefined,
        startDate: '2026-06-01',
      },
    ],
    recurringTransactions: [
      {
        ...baseRecord,
        amount: 25,
        categoryId: 'category-1',
        endDate: undefined,
        frequency: 'monthly',
        fromAccountId: 'account-1',
        interval: 1,
        isActive: true,
        lastGeneratedAt: undefined,
        lastGeneratedForDate: undefined,
        name: 'Subscription',
        nextRunDate: '2026-06-24',
        notes: undefined,
        startDate: '2026-06-01',
        toAccountId: undefined,
        type: 'expense',
      },
    ],
    transactions: [
      {
        ...baseRecord,
        amount: 25,
        categoryId: 'category-1',
        date: '2026-06-24',
        fromAccountId: 'account-1',
        linkedBillId: undefined,
        linkedGoalId: undefined,
        linkedLoanId: undefined,
        notes: 'Lunch',
        paymentMethod: 'cash',
        receiptName: undefined,
        receiptPath: undefined,
        receiptThumbnail: undefined,
        tags: ['food'],
        time: '12:00',
        toAccountId: undefined,
        transactionDateTime: '2026-06-24T12:00:00.000Z',
        type: 'expense',
      },
    ],
  } as const

  const dataSource = {
    mode: 'supabase',
    accounts: { getAll: vi.fn().mockResolvedValue(data.accounts) },
    bills: { getAll: vi.fn().mockResolvedValue(data.bills) },
    budgets: { getAll: vi.fn().mockResolvedValue(data.budgets) },
    categories: { getAll: vi.fn().mockResolvedValue(data.categories) },
    goals: { getAll: vi.fn().mockResolvedValue(data.goals) },
    loans: { getAll: vi.fn().mockResolvedValue(data.loans) },
    recurringBills: { getAll: vi.fn().mockResolvedValue(data.recurringBills) },
    recurringTransactions: {
      getAll: vi.fn().mockResolvedValue(data.recurringTransactions),
    },
    transactions: { getAll: vi.fn().mockResolvedValue(data.transactions) },
  } as unknown as FinanceDataSource

  return { data, dataSource }
}

function createHydrationInput(driver = new RecordingHydrationDriver()) {
  const { dataSource } = createMockFinanceDataSource()

  return {
    driver,
    input: {
      dataSource,
      householdId: 'household-1',
      householdSnapshot: {
        household,
        householdMembers: [
          {
            created_at: '2026-06-01T00:00:00.000Z',
            deleted_at: null,
            household_id: 'household-1',
            id: 'member-1',
            role: 'owner',
            updated_at: '2026-06-02T00:00:00.000Z',
            user_id: 'user-1',
          },
        ] satisfies LocalHouseholdMemberRow[],
      },
      localDriver: driver,
      now,
      userId: 'user-1',
    },
  }
}

describe('local SQLite hydration upsert helpers', () => {
  it('generates SQLite upsert SQL with stable params', () => {
    const statement = createLocalUpsertStatement({
      row: {
        household_id: 'household-1',
        id: 'account-1',
        name: 'Cash',
      },
      tableName: 'accounts',
    })

    expect(statement).toEqual({
      params: ['household-1', 'account-1', 'Cash'],
      sql: 'insert into accounts (household_id, id, name) values (?, ?, ?) on conflict(id) do update set household_id = excluded.household_id, name = excluded.name',
    })
  })

  it('generates metadata upsert SQL for last pulled timestamps', () => {
    const statement = createLocalSyncMetadataUpsertStatement({
      entityType: 'accounts',
      householdId: 'household-1',
      pulledAt: now.toISOString(),
    })

    expect(statement.sql).toContain('insert into local_sync_metadata')
    expect(statement.sql).toContain('last_pulled_at = excluded.last_pulled_at')
    expect(statement.params).toEqual([
      'household-1:accounts',
      'household-1',
      'accounts',
      now.toISOString(),
      null,
      null,
      now.toISOString(),
      now.toISOString(),
    ])
  })
})

describe('Supabase to local SQLite hydration', () => {
  it('reads all Supabase finance repositories with include-all options', async () => {
    const { driver, input } = createHydrationInput()

    await hydrateSupabaseToLocalSqlite(input)

    const includeAllRows = {
      includeArchived: true,
      includeDeleted: true,
    }

    expect(input.dataSource.accounts.getAll).toHaveBeenCalledWith(includeAllRows)
    expect(input.dataSource.bills.getAll).toHaveBeenCalledWith(includeAllRows)
    expect(input.dataSource.budgets.getAll).toHaveBeenCalledWith(includeAllRows)
    expect(input.dataSource.categories.getAll).toHaveBeenCalledWith(
      includeAllRows,
    )
    expect(input.dataSource.goals.getAll).toHaveBeenCalledWith(includeAllRows)
    expect(input.dataSource.loans.getAll).toHaveBeenCalledWith(includeAllRows)
    expect(input.dataSource.recurringBills.getAll).toHaveBeenCalledWith(
      includeAllRows,
    )
    expect(input.dataSource.recurringTransactions.getAll).toHaveBeenCalledWith(
      includeAllRows,
    )
    expect(input.dataSource.transactions.getAll).toHaveBeenCalledWith(
      includeAllRows,
    )
    expect(driver.transactionCalls).toBe(1)
  })

  it('runs local projection writes and metadata updates inside one transaction', async () => {
    const { driver, input } = createHydrationInput()

    const result = await hydrateSupabaseToLocalSqlite(input)

    expect(result.errors).toEqual([])
    expect(result.tables).toMatchObject({
      accounts: 1,
      bills: 1,
      budgets: 1,
      categories: 1,
      goals: 1,
      householdMembers: 1,
      households: 1,
      loans: 1,
      notifications: 4,
      recurringBills: 1,
      recurringTransactions: 1,
      transactions: 1,
    })
    expect(driver.committed).toBe(true)
    expect(driver.runs.length).toBeGreaterThan(0)
    expect(driver.runs.every((run) => run.inTransaction)).toBe(true)

    const metadataRuns = driver.runs.filter((run) =>
      run.sql.includes('insert into local_sync_metadata'),
    )

    expect(metadataRuns).toHaveLength(localHydrationEntityTypes.length)
    expect(metadataRuns.map((run) => run.params?.[2])).toEqual(
      localHydrationEntityTypes,
    )
  })

  it('soft-deletes existing local rows before upserting cloud rows', async () => {
    const { driver, input } = createHydrationInput()

    await hydrateSupabaseToLocalSqlite(input)

    expect(driver.runs[0]).toEqual({
      inTransaction: true,
      params: [now.toISOString(), now.toISOString(), 'household-1'],
      sql: 'update household_members set deleted_at = ?, updated_at = ? where household_id = ? and deleted_at is null',
    })
  })

  it('preserves deleted and archived values from cloud domain rows', async () => {
    const { driver, input } = createHydrationInput()

    await hydrateSupabaseToLocalSqlite(input)

    const accountUpsert = driver.runs.find((run) =>
      run.sql.startsWith('insert into accounts'),
    )

    expect(accountUpsert?.params).toContain('2026-06-22T00:00:00.000Z')
    expect(accountUpsert?.params).toContain('2026-06-23T00:00:00.000Z')
  })

  it('returns a clear error result and lets the driver rollback on partial failure', async () => {
    const driver = new RecordingHydrationDriver()
    driver.failOnSqlIncludes = 'insert into transactions'
    const { input } = createHydrationInput(driver)

    const result = await hydrateSupabaseToLocalSqlite(input)

    expect(result.errors).toEqual(['planned failure for insert into transactions'])
    expect(driver.rolledBack).toBe(true)
    expect(driver.committed).toBe(false)
    expect(result.tables).toEqual({
      accounts: 0,
      bills: 0,
      budgets: 0,
      categories: 0,
      goals: 0,
      householdMembers: 0,
      households: 0,
      loans: 0,
      notifications: 0,
      recurringBills: 0,
      recurringTransactions: 0,
      transactions: 0,
    })
  })
})
