import { describe, expect, it } from 'vitest'

import {
  calculateNextRecurringBillDueDate,
  isRecurringBillDue,
  validateRecurringBillInput,
} from '@/data/domain/recurring-bills'
import type { RecurringBill } from '@/data/models/recurring-bill'

const baseRecurringBill: RecurringBill = {
  id: 'recurring-bill-1',
  name: 'Electricity',
  amount: 8_000,
  categoryId: 'category-utilities',
  frequency: 'monthly',
  interval: 1,
  startDate: '2026-01-01',
  nextDueDate: '2026-01-31',
  autoGenerateDaysBeforeDue: 0,
  isActive: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
}

describe('recurring bill domain logic', () => {
  it('calculates next due dates for supported frequencies', () => {
    expect(calculateNextRecurringBillDueDate('2026-01-01', 'weekly', 2)).toBe(
      '2026-01-15',
    )
    expect(calculateNextRecurringBillDueDate('2026-01-31', 'monthly', 1)).toBe(
      '2026-02-28',
    )
    expect(calculateNextRecurringBillDueDate('2026-12-31', 'monthly', 2)).toBe(
      '2027-02-28',
    )
    expect(calculateNextRecurringBillDueDate('2024-02-29', 'yearly', 1)).toBe(
      '2025-02-28',
    )
  })

  it('detects due bills using auto-generate lead time', () => {
    expect(isRecurringBillDue(baseRecurringBill, '2026-01-31')).toBe(true)
    expect(isRecurringBillDue(baseRecurringBill, '2026-01-30')).toBe(false)
    expect(
      isRecurringBillDue(
        {
          ...baseRecurringBill,
          autoGenerateDaysBeforeDue: 7,
        },
        '2026-01-24',
      ),
    ).toBe(true)
    expect(
      isRecurringBillDue(
        {
          ...baseRecurringBill,
          lastGeneratedForDate: '2026-01-31',
        },
        '2026-01-31',
      ),
    ).toBe(false)
  })

  it('validates required recurring bill fields', () => {
    expect(() =>
      validateRecurringBillInput({
        name: '',
        amount: 8_000,
        categoryId: 'category-utilities',
        frequency: 'monthly',
        interval: 1,
        startDate: '2026-01-01',
        nextDueDate: '2026-01-31',
      }),
    ).toThrow('Bill name is required.')

    expect(() =>
      validateRecurringBillInput({
        name: 'Electricity',
        amount: 8_000,
        categoryId: '',
        frequency: 'monthly',
        interval: 1,
        startDate: '2026-01-01',
        nextDueDate: '2026-01-31',
      }),
    ).toThrow('Expense category is required.')

    expect(() =>
      validateRecurringBillInput({
        name: 'Electricity',
        amount: 8_000,
        categoryId: 'category-utilities',
        frequency: 'monthly',
        interval: 1,
        startDate: '2026-01-10',
        nextDueDate: '2026-01-09',
      }),
    ).toThrow('Next due date cannot be before start date.')
  })
})
