import type {
  RecurringBill,
  UpdateRecurringBillInput,
} from '@/data/models/recurring-bill'
import {
  nullable,
  optional,
  toSupabaseRecordFields,
  toSupabaseUpdateMetadata,
} from '@/data/supabase/mappers/mapper-utils'
import type {
  RecurringBillInsertRow,
  RecurringBillRow,
  RecurringBillUpdateRow,
  SupabaseFinanceMapperContext,
} from '@/data/supabase/supabase-finance-types'

export function fromSupabaseRecurringBillRow(row: RecurringBillRow): RecurringBill {
  return {
    id: row.id,
    name: row.name,
    amount: row.amount,
    categoryId: row.category_id,
    frequency: row.frequency,
    interval: row.interval,
    startDate: row.start_date,
    nextDueDate: row.next_due_date,
    endDate: optional(row.end_date),
    autoGenerateDaysBeforeDue: row.auto_generate_days_before_due,
    isActive: row.is_active,
    notes: optional(row.notes),
    lastGeneratedAt: optional(row.last_generated_at),
    lastGeneratedForDate: optional(row.last_generated_for_date),
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    archivedAt: optional(row.archived_at),
    deletedAt: optional(row.deleted_at),
  }
}

export function toSupabaseRecurringBillInsert(
  recurringBill: RecurringBill,
  context: SupabaseFinanceMapperContext,
): RecurringBillInsertRow {
  return {
    ...toSupabaseRecordFields(recurringBill, context),
    name: recurringBill.name,
    amount: recurringBill.amount,
    category_id: recurringBill.categoryId,
    frequency: recurringBill.frequency,
    interval: recurringBill.interval,
    start_date: recurringBill.startDate,
    next_due_date: recurringBill.nextDueDate,
    end_date: nullable(recurringBill.endDate),
    auto_generate_days_before_due: recurringBill.autoGenerateDaysBeforeDue,
    is_active: recurringBill.isActive,
    notes: nullable(recurringBill.notes),
    last_generated_at: nullable(recurringBill.lastGeneratedAt),
    last_generated_for_date: nullable(recurringBill.lastGeneratedForDate),
  }
}

export function toSupabaseRecurringBillUpdate(
  input: UpdateRecurringBillInput,
  context: Pick<SupabaseFinanceMapperContext, 'now' | 'userId'>,
): RecurringBillUpdateRow {
  const update: RecurringBillUpdateRow = toSupabaseUpdateMetadata(context)

  if ('name' in input) {
    update.name = input.name
  }

  if ('amount' in input) {
    update.amount = input.amount
  }

  if ('categoryId' in input) {
    update.category_id = input.categoryId
  }

  if ('frequency' in input) {
    update.frequency = input.frequency
  }

  if ('interval' in input) {
    update.interval = input.interval
  }

  if ('startDate' in input) {
    update.start_date = input.startDate
  }

  if ('nextDueDate' in input) {
    update.next_due_date = input.nextDueDate
  }

  if ('endDate' in input) {
    update.end_date = nullable(input.endDate)
  }

  if ('autoGenerateDaysBeforeDue' in input) {
    update.auto_generate_days_before_due = input.autoGenerateDaysBeforeDue
  }

  if ('isActive' in input) {
    update.is_active = input.isActive
  }

  if ('notes' in input) {
    update.notes = nullable(input.notes)
  }

  return update
}
