import type { RecurringBillsRepositoryContract } from '@/data/contracts'
import {
  getTodayDateString,
  isRecurringBillDue,
  mergeRecurringBillInput,
  sanitizeRecurringBillInput,
  validateRecurringBillInput,
} from '@/data/domain/recurring-bills'
import { createRecordId, createTimestamp } from '@/data/models/common'
import type {
  CreateRecurringBillInput,
  GenerateRecurringBillsResult,
  RecurringBill,
  UpdateRecurringBillInput,
} from '@/data/models/recurring-bill'
import {
  RepositoryError,
  RepositoryRecordNotFoundError,
} from '@/data/repositories/common/repository-errors'
import type { RepositoryListOptions } from '@/data/repositories/common/repository-types'
import {
  fromSupabaseRecurringBillRow,
  toSupabaseRecurringBillInsert,
  toSupabaseRecurringBillUpdate,
} from '@/data/supabase/mappers/recurring-bill-mapper'
import { throwInactiveSupabaseFinanceRepository } from '@/data/supabase/repositories/inactive-supabase-repository'
import { throwSupabaseRepositoryError } from '@/data/supabase/repositories/supabase-repository-errors'
import {
  requireSupabaseFinanceRepositoryContext,
  type SupabaseFinanceRepositoryContext,
  type SupabaseFinanceRepositoryContextInput,
} from '@/data/supabase/repositories/supabase-repository-context'
import type { RecurringBillRow } from '@/data/supabase/supabase-finance-types'
import type { Database } from '@/lib/supabase/database.types'

type RecurringBillTableRow =
  Database['public']['Tables']['recurring_bills']['Row']
type RecurringBillTableInsert =
  Database['public']['Tables']['recurring_bills']['Insert']
type RecurringBillTableUpdate =
  Database['public']['Tables']['recurring_bills']['Update']

type SupabaseRpcResult = {
  data: unknown
  error: unknown
}

type SupabaseRpcClient = {
  rpc: (
    functionName: string,
    args: Record<string, unknown>,
  ) => Promise<SupabaseRpcResult>
}

type GenerateDueRecurringBillsRpcItem = {
  recurringBillId?: unknown
  recurring_bill_id?: unknown
  scheduledDate?: unknown
  scheduled_date?: unknown
  billId?: unknown
  bill_id?: unknown
  reason?: unknown
  message?: unknown
}

type GenerateDueRecurringBillsRpcSummary = {
  generatedCount?: unknown
  generated_count?: unknown
  skippedCount?: unknown
  skipped_count?: unknown
  failedCount?: unknown
  failed_count?: unknown
  generated?: unknown
  skipped?: unknown
  failed?: unknown
}

function mapRecurringBillRow(row: RecurringBillTableRow): RecurringBill {
  return fromSupabaseRecurringBillRow(row as RecurringBillRow)
}

function createRecurringBillRecord(
  input: CreateRecurringBillInput,
): RecurringBill {
  const now = createTimestamp()
  const values = validateRecurringBillInput(input)

  return {
    id: createRecordId(),
    name: values.name,
    amount: values.amount,
    categoryId: values.categoryId,
    frequency: values.frequency,
    interval: values.interval,
    startDate: values.startDate,
    nextDueDate: values.nextDueDate,
    endDate: values.endDate,
    autoGenerateDaysBeforeDue: values.autoGenerateDaysBeforeDue ?? 0,
    isActive: values.isActive ?? true,
    notes: values.notes,
    createdAt: now,
    updatedAt: now,
  }
}

async function getSupabaseRecurringBillById(
  context: SupabaseFinanceRepositoryContext,
  id: string,
  options?: RepositoryListOptions,
) {
  let query = context.client
    .from('recurring_bills')
    .select('*')
    .eq('household_id', context.householdId)
    .eq('id', id)

  if (!options?.includeDeleted) {
    query = query.is('deleted_at', null)
  }

  if (!options?.includeArchived) {
    query = query.is('archived_at', null)
  }

  const { data, error } = await query.maybeSingle()

  if (error) {
    throwSupabaseRepositoryError('recurringBills.getById', error)
  }

  return data ? mapRecurringBillRow(data) : undefined
}

async function requireSupabaseRecurringBill(
  context: SupabaseFinanceRepositoryContext,
  id: string,
) {
  const recurringBill = await getSupabaseRecurringBillById(context, id, {
    includeArchived: true,
    includeDeleted: true,
  })

  if (!recurringBill) {
    throw new RepositoryRecordNotFoundError('Recurring bill', id)
  }

  return recurringBill
}

async function assertActiveExpenseCategory(
  context: SupabaseFinanceRepositoryContext,
  recurringBill: CreateRecurringBillInput,
) {
  if (!recurringBill.categoryId) {
    throw new RepositoryError('Expense category is required.')
  }

  const { data, error } = await context.client
    .from('categories')
    .select('id, type, archived_at, deleted_at')
    .eq('household_id', context.householdId)
    .eq('id', recurringBill.categoryId)
    .maybeSingle()

  if (error) {
    throwSupabaseRepositoryError('recurringBills.categoryCheck', error)
  }

  if (!data || data.archived_at || data.deleted_at) {
    throw new RepositoryError('Selected category is not available.')
  }

  if (data.type !== 'expense') {
    throw new RepositoryError('Selected category must be an expense category.')
  }
}

function numericRpcValue(value: unknown) {
  return typeof value === 'number' && Number.isFinite(value) ? value : 0
}

function stringRpcValue(value: unknown) {
  return typeof value === 'string' ? value : ''
}

function arrayRpcValue(value: unknown) {
  return Array.isArray(value) ? value : []
}

function normalizeRpcSummary(
  operation: string,
  data: unknown,
): GenerateDueRecurringBillsRpcSummary {
  const summary = Array.isArray(data) ? data[0] : data

  if (!summary || typeof summary !== 'object') {
    throwSupabaseRepositoryError(operation, {
      message: 'No recurring bill generation summary was returned.',
    })
  }

  return summary as GenerateDueRecurringBillsRpcSummary
}

function mapGeneratedItem(item: unknown) {
  const value = item as GenerateDueRecurringBillsRpcItem

  return {
    recurringBillId: stringRpcValue(
      value.recurringBillId ?? value.recurring_bill_id,
    ),
    scheduledDate: stringRpcValue(value.scheduledDate ?? value.scheduled_date),
    billId: stringRpcValue(value.billId ?? value.bill_id),
  }
}

function mapSkippedItem(item: unknown) {
  const value = item as GenerateDueRecurringBillsRpcItem

  return {
    recurringBillId: stringRpcValue(
      value.recurringBillId ?? value.recurring_bill_id,
    ),
    reason: stringRpcValue(value.reason) || 'Already generated.',
    scheduledDate:
      stringRpcValue(value.scheduledDate ?? value.scheduled_date) ||
      undefined,
  }
}

function mapFailedItem(item: unknown) {
  const value = item as GenerateDueRecurringBillsRpcItem

  return {
    recurringBillId: stringRpcValue(
      value.recurringBillId ?? value.recurring_bill_id,
    ),
    message: stringRpcValue(value.message) || 'Generation failed.',
    scheduledDate:
      stringRpcValue(value.scheduledDate ?? value.scheduled_date) ||
      undefined,
  }
}

function mapGenerateDueRpcResult(data: unknown): GenerateRecurringBillsResult {
  const summary = normalizeRpcSummary('recurringBills.generateDue', data)
  const generated = arrayRpcValue(summary.generated).map(mapGeneratedItem)
  const skipped = arrayRpcValue(summary.skipped).map(mapSkippedItem)
  const failed = arrayRpcValue(summary.failed).map(mapFailedItem)

  return {
    generatedCount: numericRpcValue(
      summary.generatedCount ?? summary.generated_count,
    ),
    skippedCount: numericRpcValue(
      summary.skippedCount ?? summary.skipped_count,
    ),
    failedCount: numericRpcValue(summary.failedCount ?? summary.failed_count),
    generated,
    skipped,
    failed,
  }
}

export const supabaseRecurringBillsRepository = {
  async getAll() {
    return throwInactiveSupabaseFinanceRepository()
  },
  async getById() {
    return throwInactiveSupabaseFinanceRepository()
  },
  async getDue() {
    return throwInactiveSupabaseFinanceRepository()
  },
  async create() {
    return throwInactiveSupabaseFinanceRepository()
  },
  async update() {
    return throwInactiveSupabaseFinanceRepository()
  },
  async archive() {
    return throwInactiveSupabaseFinanceRepository()
  },
  async deleteSoft() {
    return throwInactiveSupabaseFinanceRepository()
  },
  async generateDue() {
    return throwInactiveSupabaseFinanceRepository()
  },
} satisfies RecurringBillsRepositoryContract

export function createSupabaseRecurringBillsRepository(
  input: SupabaseFinanceRepositoryContextInput,
): RecurringBillsRepositoryContract {
  const context = requireSupabaseFinanceRepositoryContext(input)

  return {
    async getAll(options?: RepositoryListOptions) {
      let query = context.client
        .from('recurring_bills')
        .select('*')
        .eq('household_id', context.householdId)

      if (!options?.includeDeleted) {
        query = query.is('deleted_at', null)
      }

      if (!options?.includeArchived) {
        query = query.is('archived_at', null)
      }

      const { data, error } = await query
        .order('next_due_date', { ascending: true })
        .order('name', { ascending: true })

      if (error) {
        throwSupabaseRepositoryError('recurringBills.getAll', error)
      }

      return (data ?? []).map(mapRecurringBillRow)
    },

    async getById(id: string, options?: RepositoryListOptions) {
      return getSupabaseRecurringBillById(context, id, options)
    },

    async getDue(asOfDate = getTodayDateString()) {
      const { data, error } = await context.client
        .from('recurring_bills')
        .select('*')
        .eq('household_id', context.householdId)
        .eq('is_active', true)
        .is('archived_at', null)
        .is('deleted_at', null)
        .order('next_due_date', { ascending: true })

      if (error) {
        throwSupabaseRepositoryError('recurringBills.getDue', error)
      }

      return (data ?? [])
        .map(mapRecurringBillRow)
        .filter((recurringBill) => isRecurringBillDue(recurringBill, asOfDate))
    },

    async create(input: CreateRecurringBillInput) {
      const recurringBill = createRecurringBillRecord(input)

      await assertActiveExpenseCategory(context, recurringBill)

      const insert = toSupabaseRecurringBillInsert(recurringBill, {
        householdId: context.householdId,
        userId: context.userId,
      }) as RecurringBillTableInsert

      const { data, error } = await context.client
        .from('recurring_bills')
        .insert(insert)
        .select()
        .single()

      if (error) {
        throwSupabaseRepositoryError('recurringBills.create', error)
      }

      if (!data) {
        throwSupabaseRepositoryError('recurringBills.create', {
          message: 'No recurring bill row was returned.',
        })
      }

      return mapRecurringBillRow(data)
    },

    async update(id: string, input: UpdateRecurringBillInput) {
      const current = await requireSupabaseRecurringBill(context, id)

      if (current.archivedAt || current.deletedAt) {
        throw new RepositoryError(
          'Archived or deleted recurring bills cannot be edited.',
        )
      }

      const merged = sanitizeRecurringBillInput(
        mergeRecurringBillInput(current, input),
      )

      validateRecurringBillInput(merged)
      await assertActiveExpenseCategory(context, merged)

      const update = toSupabaseRecurringBillUpdate(merged, {
        userId: context.userId,
        now: createTimestamp(),
      }) as RecurringBillTableUpdate

      const { data, error } = await context.client
        .from('recurring_bills')
        .update(update)
        .eq('household_id', context.householdId)
        .eq('id', id)
        .select()
        .maybeSingle()

      if (error) {
        throwSupabaseRepositoryError('recurringBills.update', error)
      }

      if (!data) {
        throw new RepositoryRecordNotFoundError('Recurring bill', id)
      }

      return mapRecurringBillRow(data)
    },

    async archive(id: string) {
      const current = await requireSupabaseRecurringBill(context, id)
      const now = createTimestamp()
      const update: RecurringBillTableUpdate = {
        archived_at: current.archivedAt ?? now,
        is_active: false,
        updated_at: now,
        updated_by: context.userId,
      }

      const { data, error } = await context.client
        .from('recurring_bills')
        .update(update)
        .eq('household_id', context.householdId)
        .eq('id', id)
        .select()
        .maybeSingle()

      if (error) {
        throwSupabaseRepositoryError('recurringBills.archive', error)
      }

      if (!data) {
        throw new RepositoryRecordNotFoundError('Recurring bill', id)
      }

      return mapRecurringBillRow(data)
    },

    async deleteSoft(id: string) {
      const current = await requireSupabaseRecurringBill(context, id)
      const now = createTimestamp()
      const update: RecurringBillTableUpdate = {
        deleted_at: current.deletedAt ?? now,
        is_active: false,
        updated_at: now,
        updated_by: context.userId,
      }

      const { data, error } = await context.client
        .from('recurring_bills')
        .update(update)
        .eq('household_id', context.householdId)
        .eq('id', id)
        .select()
        .maybeSingle()

      if (error) {
        throwSupabaseRepositoryError('recurringBills.deleteSoft', error)
      }

      if (!data) {
        throw new RepositoryRecordNotFoundError('Recurring bill', id)
      }

      return mapRecurringBillRow(data)
    },

    async generateDue(asOfDate = getTodayDateString()) {
      const rpcClient = context.client as unknown as SupabaseRpcClient
      const { data, error } = await rpcClient.rpc(
        'generate_due_recurring_bills',
        {
          p_household_id: context.householdId,
          p_as_of_date: asOfDate,
          p_generated_at: createTimestamp(),
        },
      )

      if (error) {
        throwSupabaseRepositoryError('recurringBills.generateDue', error)
      }

      return mapGenerateDueRpcResult(data)
    },
  }
}
