import { Archive, CalendarClock, Pencil, Receipt, Trash2 } from 'lucide-react'

import { ActionMenu } from '@/components/app/action-menu'
import { AmountDisplay } from '@/components/app/amount-display'
import { StatusBadge } from '@/components/app/status-badge'
import { Card, CardContent } from '@/components/ui/card'
import {
  getRecurringBillFrequencyLabel,
} from '@/data/display/recurring-bill-options'
import type { Category } from '@/data/models/category'
import type { RecurringBill } from '@/data/models/recurring-bill'
import { formatDisplayDate } from '@/lib/formatting'
import { renderIconByName } from '@/lib/icon-map'
import { cn } from '@/lib/utils'

type RecurringBillCardProps = {
  categoriesById: Map<string, Category>
  onArchive: (recurringBill: RecurringBill) => void
  onDelete: (recurringBill: RecurringBill) => void
  onEdit: (recurringBill: RecurringBill) => void
  recurringBill: RecurringBill
}

function scheduleLabel(recurringBill: RecurringBill) {
  const frequency = getRecurringBillFrequencyLabel(recurringBill.frequency)

  if (recurringBill.interval === 1) {
    return `Every ${frequency.toLowerCase()}`
  }

  return `Every ${recurringBill.interval} ${frequency.toLowerCase()} cycles`
}

export function RecurringBillCard({
  categoriesById,
  onArchive,
  onDelete,
  onEdit,
  recurringBill,
}: RecurringBillCardProps) {
  const category = categoriesById.get(recurringBill.categoryId)
  const inactive =
    !recurringBill.isActive ||
    Boolean(recurringBill.archivedAt) ||
    Boolean(recurringBill.deletedAt)

  return (
    <Card>
      <CardContent className="grid gap-3 p-3 sm:grid-cols-[1fr_auto] sm:items-center">
        <div className="flex min-w-0 items-start gap-3">
          <div
            className={cn(
              'flex size-11 shrink-0 items-center justify-center rounded-lg text-white shadow-sm',
              !category && 'bg-muted text-muted-foreground',
            )}
            style={category ? { backgroundColor: category.color } : undefined}
          >
            {category ? (
              renderIconByName(category.icon, 'size-5')
            ) : (
              <Receipt className="size-5" aria-hidden="true" />
            )}
          </div>

          <div className="min-w-0 flex-1">
            <div className="flex flex-wrap items-center gap-2">
              <p className="truncate font-medium text-foreground">
                {recurringBill.name}
              </p>
              <StatusBadge tone={inactive ? 'warning' : 'info'}>
                {inactive ? 'Inactive' : 'Active'}
              </StatusBadge>
              {recurringBill.autoGenerateDaysBeforeDue > 0 ? (
                <StatusBadge tone="outline">
                  {recurringBill.autoGenerateDaysBeforeDue}d early
                </StatusBadge>
              ) : null}
            </div>
            <p className="mt-1 text-sm text-muted-foreground">
              {category?.name ?? 'Expense category'}
            </p>
            {recurringBill.notes ? (
              <p className="mt-1 text-sm leading-6 text-muted-foreground">
                {recurringBill.notes}
              </p>
            ) : null}
          </div>
        </div>

        <div className="flex items-center justify-between gap-3 sm:justify-end">
          <div className="text-left sm:text-right">
            <p className="text-sm text-muted-foreground">
              {scheduleLabel(recurringBill)}
            </p>
            <p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground sm:justify-end">
              <CalendarClock className="size-3.5" aria-hidden="true" />
              Next due {formatDisplayDate(recurringBill.nextDueDate)}
            </p>
            <p className="mt-1 text-base font-semibold">
              <AmountDisplay value={recurringBill.amount} />
            </p>
          </div>

          <ActionMenu
            label={`Open actions for ${recurringBill.name}`}
            items={[
              {
                icon: Pencil,
                label: 'Edit',
                onSelect: () => onEdit(recurringBill),
              },
              {
                disabled: inactive,
                icon: Archive,
                label: 'Archive',
                onSelect: () => onArchive(recurringBill),
              },
              {
                icon: Trash2,
                label: 'Delete',
                onSelect: () => onDelete(recurringBill),
                separatorBefore: true,
                variant: 'destructive',
              },
            ]}
          />
        </div>
      </CardContent>
    </Card>
  )
}
