import { zodResolver } from '@hookform/resolvers/zod'
import { useEffect } from 'react'
import { useForm } from 'react-hook-form'
import { z } from 'zod'

import {
  FormField,
  inputControlClassName,
  textareaControlClassName,
} from '@/components/app/form-field'
import {
  ModalDialogActions,
  ModalDialogShell,
} from '@/components/app/modal-dialog-shell'
import { Button } from '@/components/ui/button'
import {
  getTodayDateString,
  recurringBillFrequencyValues,
} from '@/data/domain/recurring-bills'
import { recurringBillFrequencyOptions } from '@/data/display/recurring-bill-options'
import type { Category } from '@/data/models/category'
import type {
  CreateRecurringBillInput,
  RecurringBill,
  UpdateRecurringBillInput,
} from '@/data/models/recurring-bill'

const recurringBillSchema = z
  .object({
    name: z.string().trim().min(1, 'Bill name is required.'),
    amount: z
      .number({ message: 'Amount must be a valid number.' })
      .finite('Amount must be a valid number.')
      .positive('Amount must be greater than 0.'),
    categoryId: z.string().trim().min(1, 'Expense category is required.'),
    frequency: z.enum(recurringBillFrequencyValues, {
      message: 'Frequency is required.',
    }),
    interval: z
      .number({ message: 'Interval must be a valid number.' })
      .int('Interval must be a whole number.')
      .min(1, 'Interval must be at least 1.'),
    startDate: z.string().trim().min(1, 'Start date is required.'),
    nextDueDate: z.string().trim().min(1, 'Next due date is required.'),
    endDate: z.string().optional(),
    autoGenerateDaysBeforeDue: z
      .number({ message: 'Auto-generate days must be a valid number.' })
      .int('Auto-generate days must be a whole number.')
      .min(0, 'Auto-generate days must be 0 or greater.'),
    isActive: z.boolean(),
    notes: z.string().trim().optional(),
  })
  .superRefine((values, context) => {
    if (values.endDate && values.endDate < values.startDate) {
      context.addIssue({
        code: 'custom',
        path: ['endDate'],
        message: 'End date cannot be before start date.',
      })
    }

    if (values.nextDueDate < values.startDate) {
      context.addIssue({
        code: 'custom',
        path: ['nextDueDate'],
        message: 'Next due date cannot be before start date.',
      })
    }
  })

type RecurringBillFormValues = z.infer<typeof recurringBillSchema>

type RecurringBillFormDialogProps = {
  open: boolean
  expenseCategories: Category[]
  recurringBill?: RecurringBill
  onClose: () => void
  onCreate: (input: CreateRecurringBillInput) => Promise<void>
  onUpdate: (id: string, input: UpdateRecurringBillInput) => Promise<void>
}

function optionalValue(value: string | undefined) {
  return value?.trim() ? value : undefined
}

function getDefaultValues(recurringBill?: RecurringBill): RecurringBillFormValues {
  const today = getTodayDateString()

  return {
    name: recurringBill?.name ?? '',
    amount: recurringBill?.amount ?? 0,
    categoryId: recurringBill?.categoryId ?? '',
    frequency: recurringBill?.frequency ?? 'monthly',
    interval: recurringBill?.interval ?? 1,
    startDate: recurringBill?.startDate ?? today,
    nextDueDate: recurringBill?.nextDueDate ?? today,
    endDate: recurringBill?.endDate ?? '',
    autoGenerateDaysBeforeDue:
      recurringBill?.autoGenerateDaysBeforeDue ?? 0,
    isActive: recurringBill?.isActive ?? true,
    notes: recurringBill?.notes ?? '',
  }
}

function buildRecurringBillInput(
  values: RecurringBillFormValues,
): CreateRecurringBillInput {
  return {
    name: values.name.trim(),
    amount: values.amount,
    categoryId: values.categoryId,
    frequency: values.frequency,
    interval: values.interval,
    startDate: values.startDate,
    nextDueDate: values.nextDueDate,
    endDate: optionalValue(values.endDate),
    autoGenerateDaysBeforeDue: values.autoGenerateDaysBeforeDue,
    isActive: values.isActive,
    notes: optionalValue(values.notes),
  }
}

export function RecurringBillFormDialog({
  expenseCategories,
  onClose,
  onCreate,
  onUpdate,
  open,
  recurringBill,
}: RecurringBillFormDialogProps) {
  const {
    formState: { errors, isSubmitting },
    handleSubmit,
    register,
    reset,
  } = useForm<RecurringBillFormValues>({
    resolver: zodResolver(recurringBillSchema),
    defaultValues: getDefaultValues(recurringBill),
  })

  useEffect(() => {
    reset(getDefaultValues(recurringBill))
  }, [open, recurringBill, reset])

  if (!open) {
    return null
  }

  async function submitForm(values: RecurringBillFormValues) {
    const input = buildRecurringBillInput(values)

    if (recurringBill) {
      await onUpdate(recurringBill.id, input)
    } else {
      await onCreate(input)
    }
  }

  return (
    <ModalDialogShell
      id="recurring-bill-form-title"
      title={recurringBill ? 'Edit Recurring Bill' : 'Add Recurring Bill'}
      description="Recurring bill schedules generate unpaid bill records only."
      maxWidthClassName="sm:max-w-2xl"
      closeDisabled={isSubmitting}
      onClose={onClose}
    >
      <form className="grid gap-4 p-5" onSubmit={handleSubmit(submitForm)}>
        <div className="grid gap-4 sm:grid-cols-2">
          <FormField label="Bill name" error={errors.name?.message}>
            <input
              className={inputControlClassName}
              placeholder="Electricity, Internet, Rent"
              {...register('name')}
            />
          </FormField>

          <FormField label="Amount" error={errors.amount?.message}>
            <input
              type="number"
              step="1"
              min="0"
              inputMode="decimal"
              className={inputControlClassName}
              {...register('amount', { valueAsNumber: true })}
            />
          </FormField>

          <FormField label="Expense category" error={errors.categoryId?.message}>
            <select className={inputControlClassName} {...register('categoryId')}>
              <option value="">Select category</option>
              {expenseCategories.map((category) => (
                <option key={category.id} value={category.id}>
                  {category.name}
                </option>
              ))}
            </select>
          </FormField>

          <FormField label="Frequency" error={errors.frequency?.message}>
            <select className={inputControlClassName} {...register('frequency')}>
              {recurringBillFrequencyOptions.map((option) => (
                <option key={option.value} value={option.value}>
                  {option.label}
                </option>
              ))}
            </select>
          </FormField>
        </div>

        <div className="grid gap-4 sm:grid-cols-4">
          <FormField label="Every" error={errors.interval?.message}>
            <input
              type="number"
              step="1"
              min="1"
              className={inputControlClassName}
              {...register('interval', { valueAsNumber: true })}
            />
          </FormField>

          <FormField label="Start Date" error={errors.startDate?.message}>
            <input
              type="date"
              className={inputControlClassName}
              {...register('startDate')}
            />
          </FormField>

          <FormField label="Next Due" error={errors.nextDueDate?.message}>
            <input
              type="date"
              className={inputControlClassName}
              {...register('nextDueDate')}
            />
          </FormField>

          <FormField
            label="Generate Early"
            error={errors.autoGenerateDaysBeforeDue?.message}
            description="Days before due date"
          >
            <input
              type="number"
              step="1"
              min="0"
              className={inputControlClassName}
              {...register('autoGenerateDaysBeforeDue', {
                valueAsNumber: true,
              })}
            />
          </FormField>
        </div>

        <div className="grid gap-4 sm:grid-cols-[1fr_auto]">
          <FormField label="End Date" error={errors.endDate?.message}>
            <input
              type="date"
              className={inputControlClassName}
              {...register('endDate')}
            />
          </FormField>
          <label className="flex min-h-10 items-center gap-2 self-end rounded-md border bg-background px-3 text-sm text-foreground shadow-sm">
            <input
              type="checkbox"
              className="size-4 accent-primary"
              {...register('isActive')}
            />
            Active
          </label>
        </div>

        {expenseCategories.length === 0 ? (
          <div className="rounded-lg border border-warning/35 bg-warning/10 px-3 py-2 text-sm leading-6 text-muted-foreground">
            No active expense categories are available. Review Settings before
            creating recurring bill schedules.
          </div>
        ) : null}

        <FormField label="Notes" error={errors.notes?.message}>
          <textarea
            className={textareaControlClassName}
            placeholder="Optional note"
            {...register('notes')}
          />
        </FormField>

        <ModalDialogActions>
          <Button
            type="button"
            variant="outline"
            disabled={isSubmitting}
            onClick={onClose}
          >
            Cancel
          </Button>
          <Button type="submit" disabled={isSubmitting}>
            {isSubmitting
              ? 'Saving...'
              : recurringBill
                ? 'Save Changes'
                : 'Add Recurring'}
          </Button>
        </ModalDialogActions>
      </form>
    </ModalDialogShell>
  )
}
