import type { RecurringBill } from '@/data/models/recurring-bill'
import type { LocalRecurringBillRow } from '@/data/local-sqlite/local-finance-row-types'
import {
  fromLocalRecordRow,
  fromSqliteBoolean,
  nullable,
  optional,
  toLocalRecordRow,
  toSqliteBoolean,
} from '@/data/local-sqlite/mappers/mapper-utils'

export function fromLocalRecurringBillRow(
  row: LocalRecurringBillRow,
): RecurringBill {
  return {
    ...fromLocalRecordRow(row),
    amount: row.amount,
    autoGenerateDaysBeforeDue: row.auto_generate_days_before_due,
    categoryId: row.category_id,
    endDate: optional(row.end_date),
    frequency: row.frequency,
    interval: row.interval,
    isActive: fromSqliteBoolean(row.is_active),
    lastGeneratedAt: optional(row.last_generated_at),
    lastGeneratedForDate: optional(row.last_generated_for_date),
    name: row.name,
    nextDueDate: row.next_due_date,
    notes: optional(row.notes),
    startDate: row.start_date,
  }
}

export function toLocalRecurringBillRow(
  recurringBill: RecurringBill,
  context: { householdId: string; userId?: string },
): LocalRecurringBillRow {
  return {
    ...toLocalRecordRow(recurringBill, context),
    amount: recurringBill.amount,
    auto_generate_days_before_due: recurringBill.autoGenerateDaysBeforeDue,
    category_id: recurringBill.categoryId,
    end_date: nullable(recurringBill.endDate),
    frequency: recurringBill.frequency,
    interval: recurringBill.interval,
    is_active: toSqliteBoolean(recurringBill.isActive),
    last_generated_at: nullable(recurringBill.lastGeneratedAt),
    last_generated_for_date: nullable(recurringBill.lastGeneratedForDate),
    name: recurringBill.name,
    next_due_date: recurringBill.nextDueDate,
    notes: nullable(recurringBill.notes),
    start_date: recurringBill.startDate,
  }
}
