import type {
  EntityId,
  FinanceRecord,
  IsoDateString,
} from '@/data/models/common'

export type RecurringBillFrequency = 'weekly' | 'monthly' | 'yearly'

export type RecurringBill = FinanceRecord & {
  name: string
  amount: number
  categoryId: EntityId
  frequency: RecurringBillFrequency
  interval: number
  startDate: IsoDateString
  nextDueDate: IsoDateString
  endDate?: IsoDateString
  autoGenerateDaysBeforeDue: number
  isActive: boolean
  notes?: string
  lastGeneratedAt?: string
  lastGeneratedForDate?: IsoDateString
}

export type CreateRecurringBillInput = {
  name: string
  amount: number
  categoryId: EntityId
  frequency: RecurringBillFrequency
  interval: number
  startDate: IsoDateString
  nextDueDate: IsoDateString
  endDate?: IsoDateString
  autoGenerateDaysBeforeDue?: number
  isActive?: boolean
  notes?: string
}

export type UpdateRecurringBillInput = Partial<CreateRecurringBillInput>

export type GenerateRecurringBillsResult = {
  generatedCount: number
  skippedCount: number
  failedCount: number
  generated: Array<{
    recurringBillId: EntityId
    scheduledDate: IsoDateString
    billId: EntityId
  }>
  skipped: Array<{
    recurringBillId: EntityId
    reason: string
    scheduledDate?: IsoDateString
  }>
  failed: Array<{
    recurringBillId: EntityId
    message: string
    scheduledDate?: IsoDateString
  }>
}
