import type { IsoDateString } from '@/data/models/common'
import type {
  CreateRecurringBillInput,
  RecurringBill,
  RecurringBillFrequency,
  UpdateRecurringBillInput,
} from '@/data/models/recurring-bill'
import { RepositoryError } from '@/data/repositories/common/repository-errors'

export const recurringBillFrequencyValues = [
  'weekly',
  'monthly',
  'yearly',
] as const

export function getTodayDateString(now = new Date()) {
  const year = now.getFullYear()
  const month = String(now.getMonth() + 1).padStart(2, '0')
  const day = String(now.getDate()).padStart(2, '0')

  return `${year}-${month}-${day}`
}

function parseDateParts(date: IsoDateString) {
  const [year, month, day] = date.split('-').map(Number)

  if (!year || !month || !day) {
    throw new RepositoryError('Date must use YYYY-MM-DD format.')
  }

  return { day, month, year }
}

function formatDate(year: number, monthIndex: number, day: number) {
  const date = new Date(year, monthIndex, day)
  const formattedYear = date.getFullYear()
  const formattedMonth = String(date.getMonth() + 1).padStart(2, '0')
  const formattedDay = String(date.getDate()).padStart(2, '0')

  return `${formattedYear}-${formattedMonth}-${formattedDay}`
}

function daysInMonth(year: number, monthIndex: number) {
  return new Date(year, monthIndex + 1, 0).getDate()
}

function addDays(date: IsoDateString, days: number) {
  const { day, month, year } = parseDateParts(date)

  return formatDate(year, month - 1, day + days)
}

export function calculateNextRecurringBillDueDate(
  scheduledDate: IsoDateString,
  frequency: RecurringBillFrequency,
  interval: number,
): IsoDateString {
  if (!Number.isInteger(interval) || interval < 1) {
    throw new RepositoryError('Interval must be at least 1.')
  }

  const { day, month, year } = parseDateParts(scheduledDate)
  const monthIndex = month - 1

  if (frequency === 'weekly') {
    return formatDate(year, monthIndex, day + interval * 7)
  }

  if (frequency === 'monthly') {
    const targetMonthIndex = monthIndex + interval
    const targetYear = year + Math.floor(targetMonthIndex / 12)
    const normalizedMonthIndex = ((targetMonthIndex % 12) + 12) % 12
    const nextDay = Math.min(
      day,
      daysInMonth(targetYear, normalizedMonthIndex),
    )

    return formatDate(targetYear, normalizedMonthIndex, nextDay)
  }

  const targetYear = year + interval
  const nextDay = Math.min(day, daysInMonth(targetYear, monthIndex))

  return formatDate(targetYear, monthIndex, nextDay)
}

export function isRecurringBillDue(
  recurringBill: RecurringBill,
  asOfDate: IsoDateString = getTodayDateString(),
) {
  if (
    !recurringBill.isActive ||
    recurringBill.archivedAt ||
    recurringBill.deletedAt
  ) {
    return false
  }

  if (
    recurringBill.endDate &&
    recurringBill.nextDueDate > recurringBill.endDate
  ) {
    return false
  }

  if (recurringBill.lastGeneratedForDate === recurringBill.nextDueDate) {
    return false
  }

  const generationDate = addDays(
    asOfDate,
    recurringBill.autoGenerateDaysBeforeDue,
  )

  return recurringBill.nextDueDate <= generationDate
}

function assertDate(value: string | undefined, label: string) {
  if (!value?.trim()) {
    throw new RepositoryError(`${label} is required.`)
  }

  parseDateParts(value)
}

function normalizeOptional(value: string | undefined) {
  const normalized = value?.trim()

  return normalized ? normalized : undefined
}

export function sanitizeRecurringBillInput(
  input: CreateRecurringBillInput,
): CreateRecurringBillInput {
  return {
    ...input,
    name: input.name.trim(),
    notes: normalizeOptional(input.notes),
    endDate: normalizeOptional(input.endDate),
    interval: Math.trunc(input.interval),
    autoGenerateDaysBeforeDue: Math.trunc(
      input.autoGenerateDaysBeforeDue ?? 0,
    ),
    isActive: input.isActive ?? true,
  }
}

export function validateRecurringBillInput(input: CreateRecurringBillInput) {
  const values = sanitizeRecurringBillInput(input)
  const autoGenerateDaysBeforeDue = values.autoGenerateDaysBeforeDue ?? 0

  if (!values.name) {
    throw new RepositoryError('Bill name is required.')
  }

  if (!Number.isFinite(values.amount) || values.amount <= 0) {
    throw new RepositoryError('Bill amount must be greater than 0.')
  }

  if (!values.categoryId?.trim()) {
    throw new RepositoryError('Expense category is required.')
  }

  if (!recurringBillFrequencyValues.includes(values.frequency)) {
    throw new RepositoryError('Frequency is required.')
  }

  if (!Number.isInteger(values.interval) || values.interval < 1) {
    throw new RepositoryError('Interval must be at least 1.')
  }

  if (
    !Number.isInteger(autoGenerateDaysBeforeDue) ||
    autoGenerateDaysBeforeDue < 0
  ) {
    throw new RepositoryError('Auto-generate days must be 0 or greater.')
  }

  assertDate(values.startDate, 'Start date')
  assertDate(values.nextDueDate, 'Next due date')

  if (values.endDate) {
    assertDate(values.endDate, 'End date')

    if (values.endDate < values.startDate) {
      throw new RepositoryError('End date cannot be before start date.')
    }
  }

  if (values.nextDueDate < values.startDate) {
    throw new RepositoryError('Next due date cannot be before start date.')
  }

  return values
}

export function mergeRecurringBillInput(
  current: RecurringBill,
  input: UpdateRecurringBillInput,
): CreateRecurringBillInput {
  return {
    name: input.name ?? current.name,
    amount: input.amount ?? current.amount,
    categoryId: input.categoryId ?? current.categoryId,
    frequency: input.frequency ?? current.frequency,
    interval: input.interval ?? current.interval,
    startDate: input.startDate ?? current.startDate,
    nextDueDate: input.nextDueDate ?? current.nextDueDate,
    endDate: 'endDate' in input ? input.endDate : current.endDate,
    autoGenerateDaysBeforeDue:
      input.autoGenerateDaysBeforeDue ?? current.autoGenerateDaysBeforeDue,
    isActive: input.isActive ?? current.isActive,
    notes: 'notes' in input ? input.notes : current.notes,
  }
}
